export const weatherCodeMap = {
  0: { text: 'Clear sky', icon: 'WiDaySunny', color: '#FFD700' },
  1: { text: 'Mainly clear', icon: 'WiDaySunnyOvercast', color: '#FFD966' },
  2: { text: 'Partly cloudy', icon: 'WiDayCloudy', color: '#FFDC73' },
  3: { text: 'Overcast', icon: 'WiCloudy', color: '#B0BEC5' },
  45: { text: 'Fog', icon: 'WiFog', color: '#B0BEC5' },
  48: { text: 'Depositing rime fog', icon: 'WiFog', color: '#B0BEC5' },
  51: { text: 'Light drizzle', icon: 'WiSprinkle', color: '#7EC8E3' },
  53: { text: 'Moderate drizzle', icon: 'WiSprinkle', color: '#6EC6E8' },
  55: { text: 'Dense drizzle', icon: 'WiRain', color: '#4FC3F7' },
  61: { text: 'Slight rain', icon: 'WiRain', color: '#4FC3F7' },
  63: { text: 'Moderate rain', icon: 'WiRain', color: '#42A5F5' },
  65: { text: 'Heavy rain', icon: 'WiShowers', color: '#2196F3' },
  71: { text: 'Slight snow', icon: 'WiSnow', color: '#E0F7FA' },
  73: { text: 'Moderate snow', icon: 'WiSnow', color: '#E0F7FA' },
  75: { text: 'Heavy snow', icon: 'WiSnowWind', color: '#DFF3F9' },
  80: { text: 'Slight rain showers', icon: 'WiRain', color: '#4FC3F7' },
  81: { text: 'Moderate rain showers', icon: 'WiRain', color: '#42A5F5' },
  82: { text: 'Violent rain showers', icon: 'WiShowers', color: '#1E88E5' },
  95: { text: 'Thunderstorm', icon: 'WiThunderstorm', color: '#FF9800' },
  96: { text: 'Thunderstorm with slight hail', icon: 'WiThunderstorm', color: '#FF9800' },
  99: { text: 'Thunderstorm with heavy hail', icon: 'WiThunderstorm', color: '#FF9800' },
}
export function codeToText(code){ return weatherCodeMap[code] || { text: 'Unknown', icon: 'WiNa', color: '#FFFFFF' } }
